baseurl: /Test
title: 'Book Management System'
description: 'This is a book management system.'
time: '2017-8-28 15:30:20'
paginate: 5
permalink: '/:title/'
jekyll-archives:
 enabled: ['categories', 'tags', 'year', 'month', 'day']
kramdown:
  input: GFM
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"

